Add database
ChoosingWaifu/java-filmorate pull request #8
Opened 2022-08-14 17:18 UTC by ChoosingWaifu

2022-08-14 17:44 UTC, ChoosingWaifu commented
не знаю что сделать, все тесты в постмане проходят, здесь почти все ошибки, не совпадают порты может быть?

2022-08-14 17:49 UTC, ChoosingWaifu commented
https://prnt.sc/B8plixUwiPS4

2022-08-14 17:51 UTC, ChoosingWaifu commented
https://pastenow.ru/72e3b859bb60c866fd389a8a6269ab94

2022-08-14 17:53 UTC, ChoosingWaifu commented
https://pastenow.ru/d0d81ae0e2bf008be8e0ffe27856e37e

2022-08-14 18:45 UTC, ChoosingWaifu commented
(комменты для наставника были)

2022-08-16 19:13 UTC, ddddemo1984 requested changes

2022-08-16 19:13 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public Collection<Genre> getFilmGenresById(long id) {
Метод вызывается только в этом же классе, так что можно поставить модификатор private. Если оставить public, то нужно написать на него тест

2022-08-16 19:13 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String query = "SELECT DISTINCT fg.GENRE_ID,g.NAME from FILMS_GENRES fg left Join Genres g on fg.GENRE_ID = g.GENRE_ID WHERE FILM_ID = ?";
Похоже здесь left Join лишний, т.к. FILMS_GENRES.GENRE_ID всегда должен быть заполнен

2022-08-16 19:13 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public void addFilmGenres(Film film) {
Аналогично, либо тест, либо private.
Также и deleteFilmGenres

2022-08-16 19:13 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public void updateFilmGenres(Film film) {
Метод не используется

2022-08-16 19:13 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        return result;
Да, так работает. Но если друзей будет много, то тащить их всех из БД на сервис - накладно по производительности и памяти. Попробуй написать логику этого метода на sql. 
Задание со звёздочкой, т.е. если не получится, не переживай, работу приму, это скорее на развитие навыков sql и на будущее

2022-08-16 19:13 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public Long makeFriends(ResultSet rs, int rowNum) throws SQLException {
Не забывай добавлять пустую строку между методами. Поправь, пожалуйста, это форматирование по всему коду

2022-08-17 11:16 UTC, merged